"""The frozen held-out batch (plan Phase 4, audit C6): draw ~30 never-compiled
campaign designs, predict them with the CURRENT model, write that down, THEN
compile them with the real p4c and score once.

WHY THIS EXISTS. Every accuracy figure the resource model carries was measured
on archives its own authors had already looked at (compiler_calibration_v6,
_extra, tcam_margin_screen, the pinned re-compiles of all three). This script
is the honest check: a seeded draw of designs nobody has compiled, whose
predictions are fixed on disk before p4c ever sees them. The rule that goes
with it: whatever the score, the model is NOT tuned in response. A miss is
logged and reported, never fitted away.

THREE STEPS, one CLI flag each, run in this order:

  --draw     Seeded draw from results/campaign_backup_20260825. Every design
             is refit from its archived best_params (scripts.replay_alignment
             .refit_pair) and, on the aligned joint arms (joint-d*), aligned
             with the CURRENT threshold alignment (align_with_policy) -- the
             Phase 3b code this batch is meant to be generated by. joint-off
             and independent are never aligned, exactly as in the campaign.
             The pair is priced by multi_model_memory_evaluation, the P4
             program is generated (the generator always emits the C5
             @placement_priority / @pa_no_overlay pragmas) and replayed end
             to end (p4_artifact_replay.replay_design) as a second,
             program-level prediction. manifest.json -- seed, git commit,
             every drawn id, every prediction, and a sha256 of every
             generated program -- is written, and the step REFUSES to run
             again over an existing manifest.
  --compile  Compiles the manifest's designs ONE AT A TIME (RAM: one p4c at a
             time, never two), each only after checking its program still
             hashes to the manifest's sha256. Resumable: a design with a
             finished compile directory and a row in compiled.csv is skipped.
  --score    Design level (stage_depth vs p4c's stages_real, blocks vs
             tcam_real) and per table (tcam_table_scoreboard.price_in_stage,
             the packer's own in-stage pricing, conditioned on the placement
             p4c actually committed). Writes design_scores.csv /
             table_scores.csv next to the manifest.

THE DRAW (draw_designs), in full:
  1. Candidates: every backup row, minus every design ALREADY COMPILED
     anywhere under results/ (compiled_identities: the (arm_slug, M, k,
     split) of every campaign-derived compile, from the calibration CSVs and
     the margin_* compile directories), minus every row whose CONTENT
     (encoding family, split, both feature lists, best_params) matches a
     compiled row's -- such a row would regenerate the same forests. Then
     content-duplicates among the candidates are collapsed to one.
  2. Candidates are sorted by (arm_slug, M, k, split) and permuted with
     numpy.random.default_rng(SEED).
  3. UNIFORM stratum: the first n_uniform rows of that order, whatever their
     prediction -- drawn before any prediction is looked at.
  4. Then the order is walked on: a row predicted at stage_depth 11-13 fills
     the DEPTH stratum while it has room; otherwise a row at 55-64 combined
     key bytes fills the BYTES stratum while it has room; otherwise it is
     passed over. The walk stops when both are full.
  "Combined key bytes" = the crossbar bytes of the design's DISTINCT
  classification keys summed: B_app + B_ddos under disjoint (one term when
  the two keys are the same fields), the one shared key's B under joint.
  N=30 splits 15 depth / 10 bytes / 5 uniform (split_counts).

Run (from the repository root), in order:
  "C:/Users/olegk/miniconda3/envs/PolimiML/python.exe" scripts/heldout_draw.py --draw
  "C:/Users/olegk/miniconda3/envs/PolimiML/python.exe" scripts/heldout_draw.py --compile
  "C:/Users/olegk/miniconda3/envs/PolimiML/python.exe" scripts/heldout_draw.py --score
"""
import argparse
import datetime
import glob
import hashlib
import itertools
import json
import os
import re
import shutil
import subprocess
import sys
import time
import traceback

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

SEED = 20260928   # the run date; fixed before the draw, never re-rolled
# The Phase 3b commit (alignment spec 2026-09-28 T1-T4, T6): the model and
# alignment code this batch is predicted and generated with. run_draw refuses
# to draw if src/ differs from it, committed or not.
PHASE3B_COMMIT = '3c511bb8918e27728f16a0c709baa78b4a1078f3'
N_DESIGNS = 30
DEPTH_BAND = (11, 13)
BYTES_BAND = (55, 64)
CAMPAIGN_BACKUP_DIR = os.path.join(ROOT, 'results', 'campaign_backup_20260825')
RESULTS_DIR = os.path.join(ROOT, 'results')
OUTPUT_ROOT = os.path.join(ROOT, 'results', 'heldout_2026_09_28')
MANIFEST = 'manifest.json'
COMPILED_CSV = 'compiled.csv'
DESIGN_SCORES_CSV = 'design_scores.csv'
TABLE_SCORES_CSV = 'table_scores.csv'
COMPILE_TIMEOUT_SECONDS = 1800

# Every CSV under results/ that records a compile of a campaign design, with
# its (source_arm_slug, M, k, split) columns. compiler_calibration_pinned has
# no such columns: its 43 designs are the rows of v6, _extra and
# tcam_margin_screen_compiled, re-compiled (see
# scripts/build_pinned_calibration_csv.py), so they are covered here.
COMPILED_SOURCE_CSVS = (
    'compiler_calibration.csv',
    'compiler_calibration_v5.csv',
    'compiler_calibration_v6.csv',
    'compiler_calibration_verify.csv',
    'compiler_calibration_extra.csv',
    'tcam_margin_screen_compiled.csv',
)
# Compile directories whose names identify a campaign design. Everything else
# under a compiles/ directory is a synthetic probe (dsp01, w003, lane_a0, ...)
# with no campaign row behind it.
_STRATUM_NAME = re.compile(r'^(independent|joint)_(low|high)_sd\d+$')
_MARGIN_NAME = re.compile(r'^margin_(.+)_M(\d+)_k(\d+)_s(\d+)$')


def split_counts(n):
    """(n_depth, n_bytes, n_uniform): about half, about a third, the rest.
    30 -> (15, 10, 5)."""
    n_depth, n_bytes = n // 2, n // 3
    return n_depth, n_bytes, n - n_depth - n_bytes


def identity(row):
    """A campaign design's identity: (arm_slug, M, k, split). Each campaign
    CSV holds one row per (M, k, split) per arm, so this is unique in the
    backup (checked by check_identities_unique)."""
    return (str(row['arm_slug']), int(row['M']), int(row['k']), int(row['split']))


def family(arm_slug):
    """'joint' or 'independent': the P4 encoding family the arm generates."""
    return 'independent' if arm_slug == 'independent' else 'joint'


def content_key(row):
    """What the refit forests depend on, arm aside: two rows with the same
    content key regenerate the same forests (refit is seeded by split)."""
    return (family(row['arm_slug']), int(row['split']),
            str(row['features_app']), str(row['features_ddos']),
            json.dumps(json.loads(row['best_params']), sort_keys=True))


def row_id_for(row):
    arm, M, k, split = identity(row)
    return 'heldout_%s_M%d_k%d_s%d' % (arm, M, k, split)


def check_identities_unique(frame):
    ids = [identity(r) for _, r in frame.iterrows()]
    if len(ids) != len(set(ids)):
        raise ValueError('campaign backup has duplicate (arm, M, k, split) rows')


def compiled_identities(results_dir=RESULTS_DIR, extra_roots=()):
    """Every campaign design compiled anywhere under results_dir, as a set of
    identity() tuples.

    From COMPILED_SOURCE_CSVS (source_arm_slug/M/k/split columns), plus every
    margin_<arm>_M<M>_k<k>_s<split> directory under any compiles/ directory.
    A <group>_<band>_sd<N> compile directory is named by stratum, not by
    design; it must resolve through one of the CSVs (it always has so far),
    and an unresolvable one raises rather than letting an unknown design
    slip through the exclusion."""
    ids, stratum_names = set(), set()
    for name in COMPILED_SOURCE_CSVS:
        path = os.path.join(results_dir, name)
        if not os.path.isfile(path):
            continue
        frame = pd.read_csv(path)
        for _, r in frame.iterrows():
            ids.add((str(r['source_arm_slug']), int(r['M']), int(r['k']),
                     int(r['split'])))
            stratum_names.add(str(r['row_id']))
    roots = [results_dir] + list(extra_roots)
    for root in roots:
        for compiles in glob.glob(os.path.join(root, '**', 'compiles'), recursive=True):
            if os.path.abspath(compiles).startswith(os.path.abspath(OUTPUT_ROOT)):
                continue
            for name in os.listdir(compiles):
                margin = _MARGIN_NAME.match(name)
                if margin:
                    ids.add((margin.group(1), int(margin.group(2)),
                             int(margin.group(3)), int(margin.group(4))))
                elif _STRATUM_NAME.match(name) and name not in stratum_names:
                    raise ValueError(
                        '%s/%s names a campaign design by stratum but no '
                        'compiled CSV says which one' % (compiles, name))
    return ids


def eligible_candidates(backup, compiled_ids):
    """(candidates, stats): the backup rows a held-out draw may use.

    Drops rows without best_params or marked infeasible, every row whose
    identity was compiled, every row whose content_key matches a compiled
    row's, and keeps only the first of any content-duplicate group (in
    identity order). Returns them sorted by identity, with stats counting
    each exclusion."""
    frame = backup.copy()
    stats = {'backup_rows': int(len(frame))}
    usable = frame['best_params'].notna()
    if 'infeasible' in frame.columns:
        usable &= frame['infeasible'].isna() | (frame['infeasible'] == '')
    frame = frame[usable]
    stats['not_refittable'] = stats['backup_rows'] - int(len(frame))
    ids = frame.apply(identity, axis=1)
    keys = frame.apply(content_key, axis=1)
    compiled_mask = ids.isin(compiled_ids)
    compiled_keys = set(keys[compiled_mask])
    stats['excluded_compiled_identity'] = int(compiled_mask.sum())
    same_content = ~compiled_mask & keys.isin(compiled_keys)
    stats['excluded_compiled_content'] = int(same_content.sum())
    frame = frame[~compiled_mask & ~same_content].copy()
    frame['_identity'] = frame.apply(identity, axis=1)
    frame = frame.sort_values('_identity')
    before = len(frame)
    frame = frame[~frame.apply(content_key, axis=1).duplicated(keep='first')]
    stats['collapsed_content_duplicates'] = int(before - len(frame))
    stats['candidates'] = int(len(frame))
    return frame.drop(columns='_identity').reset_index(drop=True), stats


def in_band(value, band):
    return value is not None and band[0] <= value <= band[1]


def draw_designs(candidates, predict, seed=SEED, n=N_DESIGNS,
                 depth_band=DEPTH_BAND, bytes_band=BYTES_BAND):
    """The seeded draw (see the module docstring, "THE DRAW").

    predict(row) -> dict with at least 'stage_depth' and 'combined_key_bytes',
    or None when the design cannot be realised (e.g. the generator refuses
    it); a None row is recorded in `skipped` and never picked.

    Returns (picks, skipped, n_examined): picks is a list of
    (category, row, prediction) in pick order, category one of 'uniform',
    'depth', 'bytes'; skipped a list of (row, reason) pairs."""
    n_depth, n_bytes, n_uniform = split_counts(n)
    order = np.random.default_rng(seed).permutation(len(candidates))
    picks, skipped = [], []
    want = {'uniform': n_uniform, 'depth': n_depth, 'bytes': n_bytes}
    got = {'uniform': 0, 'depth': 0, 'bytes': 0}
    examined = 0
    for position in order:
        if all(got[c] >= want[c] for c in want):
            break
        row = candidates.iloc[int(position)]
        examined += 1
        prediction = predict(row)
        if prediction is None:
            skipped.append((row, 'not realisable'))
            continue
        if got['uniform'] < want['uniform']:
            category = 'uniform'
        elif (got['depth'] < want['depth']
              and in_band(prediction['stage_depth'], depth_band)):
            category = 'depth'
        elif (got['bytes'] < want['bytes']
              and in_band(prediction['combined_key_bytes'], bytes_band)):
            category = 'bytes'
        else:
            continue
        got[category] += 1
        picks.append((category, row, prediction))
    return picks, skipped, examined


def combined_key_bytes(ternary_fields):
    """Crossbar bytes of a design's DISTINCT classification keys, summed.
    ternary_fields is _pool_inputs' per-table list of frozensets of
    (field_id, field_bytes)."""
    return sum(sum(nbytes for _, nbytes in key) for key in set(ternary_fields))


def sha256_of(path):
    with open(path, 'rb') as handle:
        return hashlib.sha256(handle.read()).hexdigest()


def git_head():
    return subprocess.run(['git', 'rev-parse', 'HEAD'], cwd=ROOT, capture_output=True,
                          text=True, check=True).stdout.strip()


def src_matches(commit):
    """True when src/ (the model, generator and alignment) in the working
    tree is byte-identical to `commit`'s -- committed changes and uncommitted
    ones both count. README.md files are documentation, not code, and are
    ignored."""
    out = subprocess.run(['git', 'diff', '--name-only', commit, '--', 'src'],
                         cwd=ROOT, capture_output=True, text=True, check=True).stdout
    return not [f for f in out.split() if not f.endswith('.md')]


# --- step 1: the draw ----------------------------------------------------

class _Realiser:
    """predict() for draw_designs on real campaign rows: refit, align on the
    aligned joint arms, price, generate the program, replay it. Keeps the
    generated program so a pick costs nothing more."""

    def __init__(self, output_root):
        from src.main import load_campaign_data
        self.data = load_campaign_data()
        self.p4_dir = os.path.join(output_root, 'p4_src')
        os.makedirs(self.p4_dir, exist_ok=True)

    def __call__(self, row):
        from scripts.p4_artifact_replay import replay_design
        from scripts.replay_alignment import refit_pair
        from src.p4gen.build_p4_script import (
            generate_P4_code, get_feature_intervals, get_joint_feature_intervals)
        from src.p4gen.evaluation import _pool_inputs, multi_model_memory_evaluation
        from src.training.threshold_alignment import align_with_policy

        arm = row['arm_slug']
        encoding = 'disjoint' if arm == 'independent' else 'joint'
        model_app, model_ddos, app, ddos, cols_app, cols_ddos = refit_pair(row, self.data)
        names_app = row['features_app'].split(';')
        names_ddos = row['features_ddos'].split(';')
        aligned = arm.startswith('joint-d')
        align_stats = {}
        if aligned:
            model_app, model_ddos = align_with_policy(
                model_app, model_ddos,
                app.X_val_align[:, cols_app], app.y_val_align,
                ddos.X_val_align[:, cols_ddos], ddos.y_val_align,
                align_stats=align_stats)
        usage = multi_model_memory_evaluation(model_app, model_ddos, names_app,
                                              names_ddos, encoding)
        pool = _pool_inputs(model_app, model_ddos, names_app, names_ddos, encoding)
        prediction = {
            'stage_depth': int(usage.stage_depth), 'blocks': int(usage.blocks),
            'stages': int(usage.stages),
            'combined_key_bytes': int(combined_key_bytes(pool['ternary_fields'])),
            'distinct_keys': len(set(pool['ternary_fields'])),
            'n_trees_app': len(model_app.estimators_),
            'n_trees_ddos': len(model_ddos.estimators_),
            'aligned': aligned,
            'align_accepted': align_stats.get('accepted'),
        }
        # The program, generated from the SAME (aligned) pair.
        if encoding == 'joint':
            intervals = get_joint_feature_intervals(model_app, names_app,
                                                    model_ddos, names_ddos)
            intervals_app = intervals_ddos = intervals
        else:
            intervals_app = get_feature_intervals(model_app, names_app)
            intervals_ddos = get_feature_intervals(model_ddos, names_ddos)
        row_id = row_id_for(row)
        try:
            path = generate_P4_code(
                3, 2, model_app, model_ddos,
                feature_intervals_app=intervals_app,
                feature_intervals_ddos=intervals_ddos,
                output_dir=self.p4_dir + os.sep, output_filename=row_id + '.p4',
                selected_features_app=names_app, selected_features_ddos=names_ddos)
        except ValueError as exc:
            print('  %s: generator refused it -- %s' % (row_id, exc))
            return None
        replay_depth, replay_blocks = replay_design(row_id, os.path.dirname(self.p4_dir))
        prediction.update({'replay_stage_depth': int(replay_depth),
                           'replay_blocks': int(replay_blocks),
                           'p4_path': os.path.relpath(path, ROOT).replace(os.sep, '/')})
        return prediction


def run_draw(output_root=OUTPUT_ROOT, seed=SEED, n=N_DESIGNS):
    from scripts.replay_alignment import load_backup

    manifest_path = os.path.join(output_root, MANIFEST)
    if os.path.exists(manifest_path):
        raise SystemExit('%s already exists: the draw is frozen, refusing to '
                         're-draw' % manifest_path)
    commit = git_head()
    if not src_matches(PHASE3B_COMMIT):
        raise SystemExit('src/ differs from the Phase 3b commit %s: refusing to '
                         'draw with code other than it' % PHASE3B_COMMIT)
    backup = load_backup(CAMPAIGN_BACKUP_DIR)
    check_identities_unique(backup)
    # reviews/model_audit_scratch holds re-compiles of archived designs too.
    compiled = compiled_identities(extra_roots=[os.path.join(ROOT, 'reviews')])
    candidates, stats = eligible_candidates(backup, compiled)
    stats['compiled_identities_known'] = len(compiled)
    print('candidates: %s' % stats, flush=True)
    os.makedirs(output_root, exist_ok=True)
    realise = _Realiser(output_root)
    started = time.time()
    picks, skipped, examined = draw_designs(candidates, realise, seed=seed, n=n)
    # Programs generated for rows the walk passed over are not part of the
    # batch; remove them so p4_src/ holds exactly the drawn designs.
    picked_ids = {row_id_for(row) for _, row, _ in picks}
    for path in glob.glob(os.path.join(realise.p4_dir, '*.p4')):
        if os.path.basename(path)[:-3] not in picked_ids:
            os.remove(path)
    designs = []
    for category, row, prediction in picks:
        row_id = row_id_for(row)
        p4_path = os.path.join(ROOT, prediction['p4_path'])
        designs.append({
            'row_id': row_id, 'category': category,
            'arm_slug': row['arm_slug'], 'M': int(row['M']), 'k': int(row['k']),
            'split': int(row['split']), 'group': family(row['arm_slug']),
            'predicted': {key: prediction[key] for key in (
                'stage_depth', 'blocks', 'stages', 'combined_key_bytes',
                'distinct_keys', 'replay_stage_depth', 'replay_blocks')},
            'n_trees_app': prediction['n_trees_app'],
            'n_trees_ddos': prediction['n_trees_ddos'],
            'aligned': prediction['aligned'],
            'align_accepted': prediction['align_accepted'],
            'p4_path': prediction['p4_path'],
            'p4_sha256': sha256_of(p4_path),
        })
    manifest = {
        'written_at': datetime.datetime.now().astimezone().isoformat(),
        'seed': seed,
        'git_commit': commit,
        'phase3b_commit': PHASE3B_COMMIT,
        'src_identical_to_phase3b': True,
        'script': 'scripts/heldout_draw.py',
        'source': os.path.relpath(CAMPAIGN_BACKUP_DIR, ROOT).replace(os.sep, '/'),
        'rule': {'n': n, 'split_depth_bytes_uniform': list(split_counts(n)),
                 'depth_band': list(DEPTH_BAND), 'bytes_band': list(BYTES_BAND)},
        'candidate_stats': stats,
        'rows_examined': examined,
        'skipped': [row_id_for(row) for row, _ in skipped],
        'draw_seconds': round(time.time() - started, 1),
        'designs': designs,
    }
    with open(manifest_path, 'w', encoding='utf-8') as handle:
        json.dump(manifest, handle, indent=2)
    print('wrote %s: %d designs (%s), %d rows examined, %d skipped'
          % (manifest_path, len(designs),
             {c: sum(d['category'] == c for d in designs)
              for c in ('depth', 'bytes', 'uniform')},
             examined, len(skipped)))
    return manifest


def load_manifest(output_root=OUTPUT_ROOT):
    with open(os.path.join(output_root, MANIFEST), encoding='utf-8') as handle:
        return json.load(handle)


# --- step 2: compile, one at a time -------------------------------------

def run_compile(output_root=OUTPUT_ROOT, limit=None):
    from scripts.p4_artifact_replay import _committed_blocks, committed_stages_real
    from src.p4gen.p4_compile import compile_p4, parse_compile_logs

    manifest = load_manifest(output_root)
    out = os.path.join(output_root, COMPILED_CSV)
    done = set(pd.read_csv(out)['row_id']) if os.path.exists(out) else set()
    rows = pd.read_csv(out).to_dict('records') if done else []
    todo = [d for d in manifest['designs'] if d['row_id'] not in done]
    if limit is not None:
        todo = todo[:limit]
    for design in todo:
        row_id = design['row_id']
        p4_path = os.path.join(ROOT, design['p4_path'])
        if sha256_of(p4_path) != design['p4_sha256']:
            raise SystemExit('%s: program no longer matches the manifest hash'
                             % row_id)
        compile_dir = os.path.join(output_root, 'compiles', row_id)
        os.makedirs(os.path.dirname(compile_dir), exist_ok=True)
        if os.path.isdir(compile_dir):
            shutil.rmtree(compile_dir)       # an attempt that never finished
        print('=== compiling %s (%s) ...' % (row_id, design['category']), flush=True)
        started = time.time()
        try:
            result = compile_p4(p4_path, compile_dir,
                                timeout_seconds=COMPILE_TIMEOUT_SECONDS)
        except Exception:
            traceback.print_exc()
            continue
        seconds = time.time() - started
        logs = os.path.join(compile_dir, 'pipe', 'logs')
        parsed = parse_compile_logs(compile_dir)
        blocks = _committed_blocks(logs) if os.path.isdir(logs) else None
        rows.append({
            'row_id': row_id, 'group': design['group'], 'category': design['category'],
            'stages_real': parsed.stages,
            'stages_real_committed': committed_stages_real(logs) if os.path.isdir(logs) else None,
            'tcam_real': parsed.tcam,
            'tcam_real_committed': sum(blocks.values()) if blocks else None,
            'sram_real': parsed.sram, 'map_ram_real': parsed.map_ram,
            'compile_errors': result.errors, 'compile_warnings': result.warnings,
            'compile_seconds': round(seconds, 1),
            'compiled_at': datetime.datetime.now().astimezone().isoformat(),
        })
        pd.DataFrame(rows).to_csv(out, index=False)
        print('  done in %.0fs: stages_real=%s tcam_real=%s errors=%s'
              % (seconds, parsed.stages, parsed.tcam, result.errors), flush=True)


# --- step 3: score once -------------------------------------------------

def _clean(value):
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return None
    return int(value)


def design_scores(manifest, compiled):
    """One row per design: the manifest's frozen predictions against p4c."""
    truth = {r['row_id']: r for r in compiled.to_dict('records')}
    rows = []
    for design in manifest['designs']:
        real = truth.get(design['row_id'], {})
        predicted = design['predicted']
        stages_real, tcam_real = _clean(real.get('stages_real')), _clean(real.get('tcam_real'))
        row = {'row_id': design['row_id'], 'category': design['category'],
               'group': design['group'],
               'combined_key_bytes': predicted['combined_key_bytes'],
               'distinct_keys': predicted['distinct_keys'],
               'pred_stage_depth': predicted['stage_depth'],
               'replay_stage_depth': predicted['replay_stage_depth'],
               'stages_real': stages_real,
               'pred_blocks': predicted['blocks'],
               'replay_blocks': predicted['replay_blocks'],
               'tcam_real': tcam_real,
               'compile_errors': _clean(real.get('compile_errors'))}
        row['diff_stage_depth'] = (None if stages_real is None
                                   else predicted['stage_depth'] - stages_real)
        row['diff_blocks'] = (None if tcam_real is None
                              else predicted['blocks'] - tcam_real)
        rows.append(row)
    return pd.DataFrame(rows)


def stage_orders(own, mates, not_first):
    """Candidate (ahead, behind) splits of a stage's other distinct keys for
    the key `own`: every placement order consistent with what p4c's crossbar
    says (own first, or not), since the logs cannot say which of several
    later keys came first. tcam_table_scoreboard.score_observation charges
    the WORST order the packer could emit."""
    mates = list(mates)
    if not mates:
        return [((), ())]
    orders = []
    for perm in itertools.permutations(mates):
        for cut in range(len(perm) + 1):
            if (cut > 0) == bool(not_first):
                orders.append((tuple(perm[:cut]), tuple(perm[cut:])))
    return orders


def table_scores(row_id, output_root=OUTPUT_ROOT):
    """Per table, for one compiled design: the model's per-table price
    against the blocks p4c committed to that table.

    Classification tables are priced exactly as
    scripts/tcam_table_scoreboard.py prices them (blocks_refined =
    codeword_to_blocks; blocks_charged = the packer's in-stage price given
    the other classification keys p4c put in the same stage, first-or-not
    read off the table's measured crossbar start group), times the table's
    512-row words (tree_entries_to_blocks of its declared size) -- the
    scoreboard's harvests only ever saw one-word trees. Range tables are
    priced at ceil(compiler_range_rows(size) / 512), their compile-time
    sizing (replay_program)."""
    from scripts.p4_artifact_replay import _p4_table_keys, _p4_table_sizes
    from scripts.tcam_table_scoreboard import price_in_stage
    from scripts.tcam_version_sweep import measured_start_group, read_committed
    from src.p4model.ranges import compiler_range_rows
    from src.p4model.tables import (codeword_fields_to_bytes_from_bits,
                                    codeword_to_blocks, tree_entries_to_blocks)
    from src.p4model.target import TERNARY_MATCHING_ENTRIES_PER_BLOCK

    logs = os.path.join(output_root, 'compiles', row_id, 'pipe', 'logs')
    committed = read_committed(logs)
    p4_path = os.path.join(output_root, 'p4_src', row_id + '.p4')
    tables, _, bits = _p4_table_keys(p4_path)
    sizes = _p4_table_sizes(p4_path)
    key_of = {name: tuple(sorted(tables[name])) for name in tables}
    stage_keys = {}
    for name, rec in committed.items():
        if name.startswith('get_classification_tree_'):
            stage_keys.setdefault(rec['stage'], set()).add(key_of[name])
    rows = []
    for name, rec in sorted(committed.items()):
        if name.startswith('get_classification_tree_'):
            key = key_of[name]
            key_bits = tuple(sorted(bits[f] for f in key))
            words = tree_entries_to_blocks(sizes[name])
            start_group, ambiguous = measured_start_group(rec['xbar_bytes'])
            not_first = start_group is not None and start_group > 0
            mates = [tuple(sorted(bits[f] for f in other))
                     for other in sorted(stage_keys[rec['stage']]) if other != key]
            charges, refused = [], True
            for ahead, behind in stage_orders(key_bits, mates, not_first):
                price, was_refused = price_in_stage(key_bits, ahead, behind)
                if not was_refused:
                    charges.append(price)
                    refused = False
            refined = codeword_to_blocks(key_bits)
            charged = max(charges) if charges else refined
            rows.append({
                'row_id': row_id, 'table': name, 'kind': 'classification',
                'stage': rec['stage'], 'field_bits': ','.join(map(str, key_bits)),
                'key_bytes': codeword_fields_to_bytes_from_bits(key_bits),
                'declared_size': sizes.get(name), 'row_words': words,
                'measured_start_group': start_group,
                'start_group_ambiguous': ambiguous, 'not_first': not_first,
                'distinct_keys_in_stage': len(stage_keys[rec['stage']]),
                'placement_refused': refused,
                'blocks_refined': refined * words, 'blocks_charged': charged * words,
                'observed_blocks': rec['blocks'],
            })
        elif name.startswith('table_') and name in sizes:
            predicted = -(-compiler_range_rows(sizes[name])
                          // TERNARY_MATCHING_ENTRIES_PER_BLOCK)
            rows.append({
                'row_id': row_id, 'table': name, 'kind': 'range',
                'stage': rec['stage'], 'declared_size': sizes[name],
                'placement_refused': False,
                'blocks_refined': predicted, 'blocks_charged': predicted,
                'observed_blocks': rec['blocks'],
            })
    for row in rows:
        row['diff_charged'] = row['blocks_charged'] - row['observed_blocks']
        row['diff_refined'] = row['blocks_refined'] - row['observed_blocks']
    return rows


def _tally(frame, predicted, real):
    compared = frame[frame[real].notna()]
    diff = compared[predicted] - compared[real]
    return {'n': int(len(frame)), 'compared': int(len(compared)),
            'exact': int((diff == 0).sum()), 'under': int((diff < 0).sum()),
            'over': int((diff > 0).sum()),
            'max_over': int(diff.max()) if len(diff) and diff.max() > 0 else 0,
            'max_under': int(-diff.min()) if len(diff) and diff.min() < 0 else 0}


def run_score(output_root=OUTPUT_ROOT):
    manifest = load_manifest(output_root)
    compiled = pd.read_csv(os.path.join(output_root, COMPILED_CSV))
    designs = design_scores(manifest, compiled)
    designs.to_csv(os.path.join(output_root, DESIGN_SCORES_CSV), index=False)
    table_rows = []
    for row_id in compiled['row_id']:
        table_rows += table_scores(row_id, output_root)
    tables = pd.DataFrame(table_rows)
    tables.to_csv(os.path.join(output_root, TABLE_SCORES_CSV), index=False)

    print('\n### design level (%d designs, %d compiled)' % (len(designs), len(compiled)))
    print(designs.to_string(index=False))
    summary = {
        'stage_depth': _tally(designs, 'pred_stage_depth', 'stages_real'),
        'blocks': _tally(designs, 'pred_blocks', 'tcam_real'),
    }
    live = tables[~tables['placement_refused']] if len(tables) else tables
    for kind in ('classification', 'range'):
        part = live[live['kind'] == kind]
        summary['tables_%s_charged' % kind] = _tally(part, 'blocks_charged', 'observed_blocks')
    cls = live[live['kind'] == 'classification']
    summary['tables_classification_refined'] = _tally(cls, 'blocks_refined', 'observed_blocks')
    summary['tables_refused'] = int(tables['placement_refused'].sum()) if len(tables) else 0
    for category in ('depth', 'bytes', 'uniform'):
        part = designs[designs['category'] == category]
        summary['stage_depth_%s' % category] = _tally(part, 'pred_stage_depth', 'stages_real')
        summary['blocks_%s' % category] = _tally(part, 'pred_blocks', 'tcam_real')
    with open(os.path.join(output_root, 'summary.json'), 'w', encoding='utf-8') as handle:
        json.dump(summary, handle, indent=2)
    print('\n### summary')
    print(json.dumps(summary, indent=2))
    under_tables = live[live['diff_charged'] < 0] if len(live) else live
    if len(under_tables):
        print('\n### per-table UNDER-predictions')
        print(under_tables.to_string(index=False))
    return designs, tables, summary


def main(argv=None):
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--draw', action='store_true')
    parser.add_argument('--compile', action='store_true')
    parser.add_argument('--score', action='store_true')
    parser.add_argument('--limit', type=int, default=None,
                        help='--compile: at most this many designs this run')
    parser.add_argument('--output-root', default=OUTPUT_ROOT)
    args = parser.parse_args(argv)
    if args.draw:
        run_draw(args.output_root)
    if args.compile:
        run_compile(args.output_root, limit=args.limit)
    if args.score:
        run_score(args.output_root)


if __name__ == '__main__':
    main()
